name: "Run mypy via pre-commit + reviewdog"
description: "Runs the mypy-json-output pre-commit hook on a diff range and reports diagnostics via reviewdog (RDJSON)"
author: "leinardi"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  from-ref:
    description: "Base git ref (e.g., PR base SHA)"
    required: true
  to-ref:
    description: "Head git ref (e.g., PR head SHA)"
    required: true
  github-token:
    description: "GitHub token for reviewdog (usually secrets.GITHUB_TOKEN)"
    required: true

outputs:
  exitcode:
    description: "Exit code returned by the mypy-json-output pre-commit hook"
    value: ${{ steps.mypy_lint.outputs.exitcode }}

runs:
  using: "composite"
  steps:
    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install Python deps, pre-commit
      shell: bash
      run: |
        set -euo pipefail
        pip install --no-cache-dir pre-commit

    - name: Setup reviewdog binary
      uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f
      with:
        reviewdog_version: latest

    - name: Run mypy (JSON output)
      id: mypy_lint
      shell: bash
      run: |
        set +e
        set -o pipefail

        pre-commit run mypy-json-output \
          --hook-stage manual \
          --from-ref "${{ inputs.from-ref }}" \
          --to-ref   "${{ inputs.to-ref }}" \
          --color=never \
          | tee >(grep -Ev '^\[INFO\]' | tail -n +5 > mypy.jsonl)

        exitcode=${PIPESTATUS[0]}
        echo "exitcode=$exitcode" >> "$GITHUB_OUTPUT"

        # Do not fail here; let reviewdog decide
        exit 0

    - name: Convert mypy JSON -> RDJSON
      if: steps.mypy_lint.outputs.exitcode != '0'
      shell: bash
      run: |
        # Slurp JSONL into an array and convert to RDJSON, stripping $GITHUB_WORKSPACE/ prefix.
        # The jq filter is expected at: lib/mypy-json-to-rdjson.jq
        jq -s -f "$GITHUB_ACTION_PATH/lib/mypy-json-to-rdjson.jq" mypy.jsonl > mypy.rdjson

    - name: Report mypy via reviewdog
      if: steps.mypy_lint.outputs.exitcode != '0'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        cat mypy.rdjson \
          | reviewdog \
              -f=rdjson \
              -name="mypy" \
              -reporter=github-pr-review \
              -filter-mode=nofilter \
              -fail-level=error

        # Fail the job if there were violations
        exit 1
